
version: "3.8"
services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/
      MONGO_DB_NAME: ${MONGO_DB_NAME}

  frontend:
    build: ./frontend
    container_name: frontend
    ports: 
     - "80:80"
    depends_on:
     - backend
  
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
    