sonar.projectKey=paytm
sonar.projectName=Paytm
sonar.sources=frontend/src,backend/src
sonar.javascript.lcov.reportPaths=coverage-reports/frontend/coverage/lcov.info,coverage-reports/backend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/coverage/**