sonar.projectKey=paytm
sonar.projectName=Paytm

sonar.sources=frontend/src,backend/src

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info

sonar.host.url=${SONAR_HOST_URL}
sonar.login=${SONAR_TOKEN}
sonar.exclusions=**/node_modules/**, **/coverage/**